apiVersion: v1
kind: Pod
metadata:
  name: nextcloud
spec:
  containers:
  - name: nextcloud
    image: 'nextcloud:latest'
    volumeMounts:
    - name: pd-0
      mountPath: /var/www/html/
      readOnly: false
      stdin: false
      tty: false
      restartPolicy: Always
    volumes:
    - name: pd-0
      gcePersistentDisk:
        pdName: nextcloud-data
        fsType: ext4
        readOnly: false
